workspace:
  base: /go
  path: src/github.com/UKHomeOffice/cfssl-sidekick

pipeline:
  tests:
    image: golang:1.9
    commands:
      - make test
      - make static

  latest:
    image: docker:20.10
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [docker_password]
    commands:
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick:latest . --target standard
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick-jks:latest . --target jks
      - docker login -u="ukhomeofficedigital+cfssl_sidekick" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick:latest
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick-jks:latest
    when:
      event: push
      branch: master

  tagged:
    image: docker:20.10
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [docker_password]
    commands:
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick:$${DRONE_TAG} . --target standard
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick-jks:$${DRONE_TAG} -f Dockerfile.jks . --target jks
      - docker login -u="ukhomeofficedigital+cfssl_sidekick" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick-jks:$${DRONE_TAG}
    when:
      event: tag


  branch:
    image: docker:20.10
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [ docker_password ]
    commands:
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick:$${DRONE_SHA} . --target standard
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick-jks:$${DRONE_SHA} -f Dockerfile.jks . --target jks
      - docker login -u="ukhomeofficedigital+cfssl_sidekick" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick:$${DRONE_SHA}
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick-jks:$${DRONE_SHA}
    when:
      event: push
        branch:
          exclude:
            - main
