workspace:
  base: /go
  path: src/github.com/UKHomeOffice/cfssl-sidekick

pipeline:
  tests:
    image: golang:1.9
    commands:
      - make test
      - make static

  latest:
    image: docker:1.13
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [docker_password]
    commands:
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick:latest .
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick-jks:latest -f Dockerfile.jks .
      - docker login -u="ukhomeofficedigital+cfssl_sidekick" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick:latest
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick-jks:latest
    when:
      event: push
      branch: master

  tagged:
    image: docker:1.13
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [docker_password]
    commands:
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick:$${DRONE_TAG} .
      - docker build -t quay.io/ukhomeofficedigital/cfssl-sidekick-jks:$${DRONE_TAG} -f Dockerfile.jks .
      - docker login -u="ukhomeofficedigital+cfssl_sidekick" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/cfssl-sidekick-jks:$${DRONE_TAG}
    when:
      event: tag

  scan:
       # The location of the drone plugin
     image: quay.io/ukhomeofficedigital/anchore-submission:latest
       # The optional path of a Dockerfile
     dockerfile: Dockerfile
       # Note the lack of double $ here (due to the way drone injects variables"
     image_name: quay.io/ukhomeofficedigital/cfssl-sidekick:latest
       # This indicates we are willing tolerate any vulnerabilities which are below medium
     tolerates: medium

     fail_on_detection: false

     when:
       event: [push, tag]
