FROM quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.9
MAINTAINER Rohith Jayawardene <gambol99@gmail.com>

USER root
RUN apk add openjdk8-jre-base bash openssl --no-cache
ADD scripts/create-keystore.sh /usr/bin/create-keystore.sh

RUN mkdir -p /etc/ssl/java && \
    cp -r /etc/ssl/certs/java/cacerts /etc/ssl/java

USER 1000
