FROM quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.3
MAINTAINER Rohith Jayawardene <gambol99@gmail.com>

USER root
RUN apk add openjdk8-jre-base bash openssl --no-cache
ADD scripts/create-keystore.sh /usr/bin/create-keystore.sh

USER 1000
