apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: example
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: bundle
        configMap:
          name: bundle
      - name: keystore
        emptyDir: {}
      - name: certs
        emptyDir: {}
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick:latest
        securityContext:
          runAsNonRoot: true
        args:
        - --certs=/certs
        - --domain=example.${KUBE_NAMESPACE}.svc.cluster.local
        - --domain=localhost
        - --expiry=8760h
        env:
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEYSTORE_PASSWORD
          value: anythingelse
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: bundle
          mountPath: /etc/ssl/certs
          readOnly: true
      - name: certs-jks
        image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:latest
        securityContext:
          runAsNonRoot: true
        args:
        - --certs=/certs
        - --command=/usr/bin/create-keystore.sh
        - --domain=example.${KUBE_NAMESPACE}.svc.cluster.local
        - --domain=localhost
        - --expiry=8760h
        env:
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: keystore
          mountPath: /etc/keystore
        - name: bundle
          mountPath: /etc/ssl/certs
          readOnly: true
